### PR TITLE
Merge the two flip-platform branches

### PR DESCRIPTION
**Pull request by AxlLind**
There are two branches for the flip-platform. Since we already have a pull request for the main one I'll just merge this into that pull request.

### CODE REVIEW

**Comment by Jontpan** [comment]
Yeah, problem with that was that flips-with-pause was much more of a testing branch, and i believe master now has flips in the first platformscheme...

**Comment by Jontpan** [comment]
I'll fix this in this commit I'm pushing now.

**Comment by AxlLind** [comment]
Oh sorry, my bad.

**Comment by Jontpan** [comment]
we should maybe create a testing branch? Where the first platformscheme is always the latest platformtype and never delete the branch

**Pull request merged**
