### PR TITLE
Fix bug #54

### PR DESCRIPTION
**Pull request by Jontpan**
I had moved the moving portion to update isteand of fixedupdate, but the
pause logic was still in fixedupdate
Moved pause check to update

### CODE REVIEW

**Comment by AxlLind** [comment]
Hmm.. Shouldn't the code for moving the platform be in fixedUpdate anyway, since it affects a physics object?

**Review by AxlLind — COMMENTED** [review]
Hmm.. Shouldn't the code for moving the platform be in fixedUpdate anyway, since it affects a physics object?

**Comment by Jontpan** [comment]
mmmmaybe. It was somehow kinda jittery when it was in fixed but logically that would make sense.,

**Comment by AxlLind** [comment]
Yes, you're right. Just tested it out and the platform movement is a bit less smooth in FixedUpdate. I didn't notice any strange physics behaviour with them in Update so we might just keep the code in Update unless we do notice bugs.

**Pull request merged**
